---
deployment:
  tasks:
    - export DEPLOYPATH=/home/m4e91ghcu0pb/public_html/bpa-demo/
    - /bin/cp -R * $DEPLOYPATH
    - export DEPLOYPATH=/home/m4e91ghcu0pb/public_html/workspace.xebrain.com/
    - /bin/cp -R * $DEPLOYPATH
